//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<empleado> empleados { get; set; }
        public virtual DbSet<modulo> modulos { get; set; }
        public virtual DbSet<oficina> oficinas { get; set; }
        public virtual DbSet<pedido> pedidos { get; set; }
        public virtual DbSet<producto> productos { get; set; }
        public virtual DbSet<tree_menu> tree_menu { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
