//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidos
    {
        public int Id { get; set; }
        public string numpedido { get; set; }
        public Nullable<System.DateTime> fechapedido { get; set; }
        public int clie { get; set; }
        public string fab { get; set; }
        public string producto { get; set; }
        public Nullable<int> cant { get; set; }
        public Nullable<decimal> importe { get; set; }
    }
}
