//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tree_menu
    {
        public int Id { get; set; }
        public Nullable<int> id_modulo { get; set; }
        public Nullable<int> id_item { get; set; }
        public Nullable<int> id_item_padre { get; set; }
        public string ejecuta { get; set; }
        public Nullable<int> orden { get; set; }
        public string titulo { get; set; }
        public Nullable<int> grupo { get; set; }
        public string icono { get; set; }
    }
}
