//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProyect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class modulos
    {
        public int Id { get; set; }
        public string descrip { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<int> habilitado { get; set; }
    }
}
