//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProyect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public decimal ID { get; set; }
        public string USERNAME { get; set; }
        public string USERFULLNAME { get; set; }
        public string PASSWORD { get; set; }
        public string SALT { get; set; }
        public string EMAIL { get; set; }
        public string ACCOUNTTYPE { get; set; }
        public Nullable<System.DateTime> LASTLOGIN { get; set; }
    }
}
