//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleados
    {
        public int numemp { get; set; }
        public string nombre { get; set; }
        public Nullable<int> edad { get; set; }
        public int oficina { get; set; }
        public string titulo { get; set; }
        public Nullable<System.DateTime> contrato { get; set; }
        public Nullable<int> jefe { get; set; }
        public Nullable<decimal> cuota { get; set; }
        public Nullable<decimal> ventas { get; set; }
    }
}
