//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionEntities : DbContext
    {
        public GestionEntities()
            : base("name=GestionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<empleados> empleados { get; set; }
        public virtual DbSet<Localidades> Localidades { get; set; }
        public virtual DbSet<modulos> modulos { get; set; }
        public virtual DbSet<oficinas> oficinas { get; set; }
        public virtual DbSet<pedidos> pedidos { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<Tipos_Documento> Tipos_Documento { get; set; }
        public virtual DbSet<tree_menu> tree_menu { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
