//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class oficinas
    {
        public int oficina { get; set; }
        public string ciudad { get; set; }
        public string region { get; set; }
        public Nullable<int> dir { get; set; }
        public Nullable<decimal> objetivo { get; set; }
        public Nullable<decimal> ventas { get; set; }
    }
}
